wpilibsuite/systemcore-blocks-interface

src/App.tsx, src/editor/editor.ts, src/editor/extended_python_generator.ts, src/storage/client_side_storage.ts, src/storage/common_storage.ts
Added mechanisms to the app (new mechanism, show mechanism in the tree, rename/copy mechanism, etc).
Set the title of the workspace name modal bases on what is being done (new workspace, rename workspace, copy workspace). Set the title of the module name modal bases on what is being done (new workspace, rename workspace, copy workspace).
Fixed a problem where the module type wasn't being passed to the python generator when it generates the python code for the UI.
When a new module is selected and we are updating the blocks editor area, close the toolbox flyout if it is open.
When saving a module to storage, include the module type. Improved the code that writes and reads modules (Workspaces, Mechanisms, and OpModes) to/from storage.
=> Added mechanism modules to the app

README.md, src/editor/extended_python_generator.ts, src/modules/mechanism_start.json, src/modules/robot_start.json, src/storage/common_storage.ts
This adds default blocks for the mechanism and the workspace (Robot) class
=> Default blocks

README.md, src/App.tsx, src/blocks/mrc_call_python_function.ts, src/blocks/mrc_get_python_variable.ts, src/blocks/mrc_set_python_variable.ts, src/editor/editor.ts, src/editor/extended_python_generator.ts, src/storage/client_side_storage.ts, src/storage/common_storage.ts, src/toolbox/toolbox.ts
Change the "Workspace" terminology to "Project" so it won't conflict with the idea of a Blockly Workspace.
Fixes #36
=> Change the "Workspace" terminology to "Project"

package-lock.json, package.json, src/App.tsx, src/storage/client_side_storage.ts, src/storage/common_storage.ts
=> Implemented download project and upload project.

src/blocks/mrc_class_method_def.ts, src/editor/extended_python_generator.ts
=> Remove duplicate comment from methods

docs/design.md
Here is my beginning of trying to capture some of what has been said.   I am sure I have done this imperfectly and this may cause a lot of discussion.
Closes #66
=> Start of design doc

src/blocks/mrc_call_python_function.ts
Make mrc_call_python_function work for calling methods in the same class.
Fixes #64
=> Make mrc_call_python_function work for calling methods in the same class.

src/App.tsx, src/blocks/mrc_class_method_def.ts, src/editor/editor.ts, src/editor/extended_python_generator.ts, src/editor/generator_context.ts, src/storage/common_storage.ts
Fixed #63
Added generator_context.ts with class GeneratorContext, which holds information needed during and after python code generation:
- The module (so the ExtendedPythonGenerator can get the class and parent class names)
- Exported blocks (these are produced by the ExtendedPythonGenerator and are added to the file after code generation is finished).
- The class method names (maps from the block's NAME field to the actual python method name)
- Method getClassName returns the class name as PascalCase.
Modified ExtendedPythonGenerator so it can safely be a singleton.
- Removed fields currentModule and mapWorkspaceIdToExportedBlocks and added context (type GeneratorContext).
- Renamed methods_ field to classMethods. This field can stay in ExtendedPythonGenerator because it is only needed …
=> Modified ExtendedPythonGenerator so it can safely be a singleton

src/blocks/mrc_class_method_def.ts, src/blocks/mrc_mechanism.ts, src/blocks/setup_custom_blocks.ts, src/editor/extended_python_generator.ts, src/editor/generator_context.ts
Fixes #29
This was the simplest way I could come up with to make all variables part of the class (using self.).  It allows us to use all the normal built-in blockly things instead of needing to duplicate them.
=> Make all variables class instance variables

src/blocks/mrc_call_python_function.ts, src/blocks/mrc_class_method_def.ts, src/editor/extended_python_generator.ts, src/editor/generator_context.ts, src/toolbox/methods_category.ts
Handle method names that are python reserved words.
Fixes #73   
Update mrc_call_python_function blocks in the same blockly workspace when the method name on a mrc_class_method_def block is changed.
(This does not close 71 because does not update callers if a parameter or the return type changes.
=> Handle method names that are python reserved words.

src/App.tsx, src/modal/NewModuleNameModal.tsx, src/modal/NewProjectNameModal.tsx, src/storage/client_side_storage.ts, src/storage/common_storage.ts
Fixes #57 
Force class names to start with uppercase letter
Fixes #75
The new Project/OpMode/Mechanism dialog should ask for the class name (PascalCase) 
Fixes #76 
The tree should show the class names not the file names
Fixes #77 
The Module class (in common_storage.ts) should have a field for className
=> Ask for class name (instead of module/file name) in dialog boxes

docs/design.md
State explicitly that we don't allow multiple methods to be created with the same name
=> Added limitation to design doc

src/blocks/mrc_call_python_function.ts, src/blocks/mrc_class_method_def.ts
Update parameters for call blocks in the same blockly workspace if a method def block is changed.
Fixes #71
=> Update parameters for call block when method args are changed.

src/App.tsx, src/blocks/mrc_call_python_function.ts, src/blocks/mrc_class_method_def.ts, src/blocks/mrc_get_python_enum_value.ts, src/blocks/mrc_get_python_variable.ts, src/blocks/mrc_mechanism.ts, src/blocks/mrc_misc_comment.ts, src/blocks/mrc_set_python_variable.ts, src/editor/editor.ts, src/editor/extended_python_generator.ts, src/editor/generator_context.ts, src/modal/NewModuleNameModal.tsx, src/modal/NewProjectNameModal.tsx, src/storage/client_side_storage.ts, src/storage/common_storage.ts, src/toolbox/items.ts, src/toolbox/mechanism_class_methods.ts, src/toolbox/methods_category.ts, src/toolbox/opmode_class_methods.ts, src/toolbox/robot_class_methods.ts, src/toolbox/settings.tsx, src/toolbox/toolbox.ts, src/toolbox/toolbox_tests.ts
Fixed all warnings except one in App.tsx:  "Could not find a declaration file for module './Blockly'. '/Users/lizlooney/wpilib/1/systemcore-blocks-interface/src/Blockly/index.js' implicitly has an 'any' type."
=> Fixed all warnings except one

src/reactComponents/ModuleOutline.tsx
This fixes a bug where you couldn't create a new project if you didn't currently have one.  It came due to a cut/paste error when I was refactoring
=> HandleNewProject shouldn't require a project

external_samples/color_range_sensor.py, external_samples/component.py, external_samples/rev_touch_sensor.py, external_samples/servo.py, external_samples/smart_motor.py, external_samples/sparkfun_led_stick.py
Follow Semantic versioning here: https://semver.org/
=> Change to semantic versioning for components

src/editor/extended_python_generator.ts
Fixed uses of getAllVariables and getVariableUsesById, which are deprecated in v12 and will be deleted in v13.
=> Fixed uses of deprecated blockly functions

src/App.tsx, src/blocks/mrc_mechanism_component_holder.ts, src/toolbox/blocks_components.ts, src/toolbox/hardware_category.ts
This makes it so that in a mechanism, the components list is updated based off of what components are in the mechanism
=> Make components real

src/toolbox/hardware_category.ts
I realized that there was nothing to stop the robot module from using the same getComponents code that the mechanism module uses.
=> Change robot module to also use real getComponents code

src/App.tsx
This changes the code to be a sider (like the menu), so it looks the same.     I also put in the colors so it is all dark.
(Fixes #113)
=> Changes code to sider, colors

package-lock.json, package.json, src/App.tsx
Found out (via error in javascript console) that you need the compatibility patch for antd 5.x if you are using React 19.   This is one option.  The other option is we could go back to React 18.
=> Add ant design compatibility patch for working with React 19.

src/toolbox/hardware_category.ts
Fixes the problem you noticed in PR #136
=> Robot now shows ports for a component

src/blocks/mrc_call_python_function.ts, src/blocks/mrc_mechanism_component_holder.ts, src/editor/editor.ts, src/toolbox/hardware_category.ts
Moved code that iterates through the components blocks in a holder block from hardware_category.ts to mrc_mechanism_component_holder.ts.
Added code to editor.ts to get the names of components from the robot. Added code to mrc_call_python_function.ts to populate the dropdown in blocks that call component instance methods.
=> Populate the dropdown in blocks that call component instance methods

src/blocks/mrc_component.ts, src/blocks/mrc_get_parameter.ts, src/blocks/mrc_port.ts, src/blocks/utils/python.ts, src/editor/editor.ts, src/reactComponents/Tabs.tsx, src/reactComponents/ThemeModal.tsx, src/toolbox/hardware_category.ts
This fixes the TS errors.
I didn't fix the error that the generated JSON from the samples doesn't meet the definition of PythonCode because I didn't know whether you wanted to fix it in the generator or in the definition of PythonCode.
=> Fix TS errors

src/blocks/mrc_call_python_function.ts, src/editor/editor.ts, src/toolbox/blocks_mechanisms.ts, src/toolbox/hardware_category.ts
Fill the Robot -> Components category on the toolbox when the user is editing an opmode.
Commented out fake code.
=> Fill the Robot -> Components category

src/reactComponents/CodeDisplay.tsx
While in this file, I also made the header a little less ugly.
=> Fix Python code display growing to be taller than blockly component

src/modules/opmode_start.json, src/storage/client_side_storage.ts, src/storage/common_storage.ts
Every new project now has a robot and a Teleop opmode.
=> Change new projects to have Teleop as default OpMode

src/editor/editor.ts, src/storage/client_side_storage.ts, src/storage/common_storage.ts
The JSON contains the module type, blocks, components, events, and methods.
=> Save JSON only (no python) when saving each module.

src/reactComponents/Menu.tsx, src/storage/client_side_storage.ts, src/storage/common_storage.ts, src/storage/create_python_files.ts
I also had to change the module name to be robot instead of the project so that the robot file would be downloaded as "robot.py"
=> Deploy now downloads a zip of all python files

server_python_scripts/blocks_base_classes/robot_base.py, src/blocks/mrc_mechanism_component_holder.ts, src/editor/extended_python_generator.ts
Add define_hardware method to RobotBase and call it from RobotBase.__init__.
Modified mrc_mechanism_component_holder pythonFromBlock to determine the module type by calling generator.getModuleType() instead of checking for the presence of the mechanisms input.
Modified ExtendedPythonGenerator.generateInitStatements to not generate the call so self.define_hardware() if the module type is robot.
Modified ExtendedPythonGenerator.finish to generate the __init__ method before other methods.
=> Make RobotBase.__init__ call self.define_hardware()

src/blocks/mrc_event.ts, src/blocks/mrc_event_handler.ts, src/editor/editor.ts, src/editor/extended_python_generator.ts, src/storage/common_storage.ts, src/toolbox/event_category.ts, src/toolbox/hardware_category.ts, src/toolbox/methods_category.ts
In common_storage.ts, added function makeUniqueName. Modified makeUploadProjectName to call makeUniqueName.
In editor.ts, added methods getCurrentModuleType and getEventHandlerNames. Removed fields methodsCategory and eventsCategory, but still create all custom toolbox categories in the constructor.
In mrc_event_handler.ts, renamed function getHasEventHandler to getHasAnyEnabledEventHandlers. Added function getEventHandlerNames.
In mrc_event.ts, modified createCustomEventBlock to take the event name as a parameter.
In hardware_category.ts, renamed functions that return a category to be named get...Category instead of get...Blocks. Make RobotEventsCategory a custom category with a flyout callback.
In event_category, removed field currentModule and method setCurrentModule. Make a unique …
=> Don’t allow 2 event handlers for the same event in the same module

src/blocks/mrc_call_python_function.ts, src/blocks/mrc_component.ts, src/blocks/mrc_mechanism.ts, src/editor/editor.ts, src/storage/common_storage.ts, src/toolbox/hardware_category.ts, src/toolbox/methods_category.ts
Show mechanism methods in the toolbox.
=> Show mechanism methods in the toolbox

src/blocks/mrc_call_python_function.ts, src/blocks/mrc_event.ts, src/blocks/mrc_event_handler.ts, src/blocks/mrc_get_parameter.ts, src/blocks/mrc_mechanism.ts
=> Make warning bubbles visible.

src/reactComponents/Menu.tsx, src/reactComponents/ProjectManageModal.tsx, src/storage/client_side_storage.ts, src/storage/common_storage.ts, src/storage/names.ts, src/storage/project.ts
Removed functions related to projects from the Storage interface. Added code to project.ts to handle project stuff.
This will make implementing the server side storage easier.
=> Refine Storage interface

src/blocks/mrc_mechanism.ts, src/storage/module.ts, src/storage/module_content.ts, src/storage/project.ts
Added moduleId to Module and ModuleContent.
Updated mrc_mechanism to find the mechanism by its module id.
=> Update the mechanism block in the robot if the mechansim module name has been changed

src/blocks/mrc_call_python_function.ts, src/blocks/mrc_class_method_def.ts, src/blocks/mrc_component.ts, src/blocks/mrc_event_handler.ts, src/blocks/mrc_mechanism_component_holder.ts, src/editor/editor.ts, src/editor/extended_python_generator.ts, src/editor/generator_context.ts, src/reactComponents/AddTabDialog.tsx, src/reactComponents/FileManageModal.tsx, src/reactComponents/Menu.tsx, src/reactComponents/Tabs.tsx, src/storage/client_side_storage.ts, src/storage/module.ts, src/storage/module_content.ts, src/storage/names.ts, src/storage/project.ts, src/toolbox/hardware_category.ts, src/toolbox/methods_category.ts, src/toolbox/toolbox.ts
Store modules with double extension: .robot.json, .mechanism.json, .opmode.json.
=> Store modules with double extension: .robot.json, .mechanism.json, .opmode.json.

package-lock.json, package.json, src/editor/editor.ts, src/storage/client_side_storage.ts, src/storage/common_storage.ts, src/storage/create_python_files.ts, src/storage/module_content.ts, src/storage/names.ts, src/storage/project.ts
Store version number in project.info.json
=> Store version number in project.info.json

src/blocks/mrc_list_add_item.ts, src/blocks/mrc_math_min_max.ts, src/blocks/mrc_misc_comment.ts, src/blocks/mrc_misc_evaluate_but_ignore_result.ts
Fixed some fileoverview comments.
=> Fixed some fileoverview comments.

src/blocks/mrc_get_python_variable.ts, src/blocks/mrc_set_python_variable.ts
Share VariableKind enum for get and set python variable blocks.
Remove VariableKind in mrc_set_python_variable.ts.
Use VariableKind from mrc_get_python_variable.ts.
=> Share VariableKind enum for get and set python variable blocks

src/i18n/locales/en/translation.json, src/i18n/locales/es/translation.json, src/i18n/locales/he/translation.json, src/reactComponents/ClassNameComponent.tsx, src/reactComponents/ProjectNameComponent.tsx
Removed addTabDialog.newItemPlaceholder which was not used in the AddTabDialog.
It was used in the ClassNameCompoonent and ProjectNameComponent but "Add Module" doesn't make sense there.
=> Removed i18n string addTabDialog.newItemPlaceholder

src/blocks/mrc_port.ts, src/fields/field_number_dropdown.ts
Simple change so ports are dropdowns instead of fill in numeric fields
=> Change ports to be dropdown

src/blocks/mrc_call_python_function.ts, src/blocks/mrc_event_handler.ts, src/blocks/mrc_mechanism.ts, src/editor/editor.ts
In blocks that have an mrcOnLoad method, create a method called mrcValidate. Make mrcOnLoad call mrcValidate.
In editor.makeCurrent, call the mrcValidate method on all blocks that implement it.
Fixes #237
=> Make necessary changes to blocks when changing tabs

src/App.tsx, src/i18n/locales/en/translation.json, src/i18n/locales/es/translation.json, src/i18n/locales/he/translation.json, src/reactComponents/CodeDisplay.tsx, src/reactComponents/SiderCollapseTrigger.tsx
This fixes #231.   
It also has some changes to the left menu so that the two would use the same component so they look and act the same.
=> Allow code panel to be resized

src/blocks/mrc_class_method_def.ts, src/blocks/mrc_event.ts, src/blocks/mrc_event_handler.ts, src/blocks/mrc_get_parameter.ts, src/editor/editor.ts
Update mrc_get_parameter to respond to mrcOnMove and mrcOnAncestorMove, instead of using change_framework.
=> Update mrc_get_parameter to respond to mrcOnMove and mrcOnAncestorMove

src/reactComponents/FileManageModal.tsx, src/reactComponents/ManageTable.tsx, src/reactComponents/ProjectManageModal.tsx
Fixes #255 
It turned out that there was a lot of logic specific to it being a project or a file, but pulling the table into a common component was fairly straightforward and I think worthwhile.
=> Pull table out of each dialog into common component
